services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    ports:
      - "0.0.0.0:5232:5232"
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./radicale/data:/data
      - ./radicale/config:/config
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/config.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/sites/:/usr/share/sites/

    
